### ISSUE TITLE
unicode character counter 

### ISSUE THREAD

**Issue by weejulius** [SimonWang9610/gpt_tokenizer#2]
thanks for your tokenizer library.

I have an issue regarding the counter of chinese character. it seems the result is diff from https://platform.openai.com/tokenizer. for example the counter of library is 2 using the string '中文', however it is 3 from https://platform.openai.com/tokenizer.

I am not sure the reason of the difference, need I preprocess anything?

**Comment by SimonWang9610** [comment]
It is wired, I guess it may be related to the encoding of Chinese characters. 

Anyway, I will do more investigation about Chinese characters as soon as possible.

**Comment by SimonWang9610** [comment]
It should be related to the tiktoken file for a specific `modelName`.

[https://platform.openai.com/tokenizer](https://platform.openai.com/tokenizer) uses the encoding file (`p50k_base.tiktoken`) for `gpt-3` model by default.
<img width="739" alt="openai-official" src="https://user-images.githubusercontent.com/55259373/230117157-9cc67166-2b06-4c4e-b1be-3144d9bc0eff.png">

 In contrast, this package supports all encoding files: `cl100k_base`, `p50k_base`, `r50k_base`, `p50k_edit`, `r50k_edit`.

By specifying a different `modelName`, it would use the corresponding encoding file. See the below snapshots:

<img width="676" alt="gpt3" src="https://user-images.githubusercontent.com/55259373/230116745-7ab325f3-9494-442a-b790-783e03b69314.png">
<img width="678" alt="gpt4" src="https://user-images.githubusercontent.com/55259373/230116772-b35cebbe-5606-4b1d-8a67-e9e6d2818cfd.png">

You could find the mapping between `modelName` and their encoding files. [here](https://github.com/SimonWang9610/gpt_tokenizer/blob/main/packages/flutter_gpt_tokenizer/lib/src/tokenizer/constants.dart)
