### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by QSD-Edvard** [SimonWang9610/gpt_tokenizer#5]
On flutter [pub.dev page](https://pub.dev/packages/flutter_gpt_tokenizer/score) you said this library has support for Android/iOS/Windows/Linux/Mac, but no support for Web.

Do you have any plans for adding it too?
Thanks

**Comment by SimonWang9610** [comment]
> On flutter [pub.dev page](https://pub.dev/packages/flutter_gpt_tokenizer/score) you said this library has support for Android/iOS/Windows/Linux/Mac, but no support for Web.
> 
> 
> 
> Do you have any plans for adding it too?
> 
> Thanks

Currently not, coz it needs some time to research if the compiled wasm could be loaded correctly. More specifically, there are some cross-origin issues of loading wasm in flutter web.
